### ISSUE TITLE
Not working inside loop in Raspberry Pi

### ISSUE THREAD

**Issue by squgeim** [gvalkov/python-evdev#37] opened 2015-09-04 22:16 UTC
I am trying to do a mouse button click when I receive some input from serial in Raspberry Pi. When done in a shell with just evdev, it works, but when done inside a loop that monitors the serial, it does not work. It gives no error or any message in the shell. The same code works in a laptop though.

Is is an issue with the Raspberry Pi (ArchLinuxARM) or some issue inside python-evdev?

**Comment by ssieb** [comment] 2015-09-04 22:57
It would be easier to help if you could provide the actual code sample.

**Comment by squgeim** [comment] 2015-09-05 02:05
Here is the kind of situation I'm talking about:
    from evdev import ecodes as e, UInput
    if __name__=='__main__':
      s = serial.Serial('/dev/ttyUSB0',9600)
      while(True):
        if s.inWaiting() > 0:
          data = s.read().decode().strip()
          if data!='':
            print(data)
            if data=='6':
              print('inside 6')
              u = UInput({e.EV_KEY : (e.BTN_LEFT, e.BTN_RIGHT)})
              u.write(e.EV_KEY,e.BTN_LEFT,1)
              u.write(e.EV_KEY,e.BTN_LEFT,0)
              u.syn()

This code works in a laptop, but not in a Raspberry Pi. I know that the code has reached the inner block as the print is executed, but the mouse click doesn't happen.

Executing just the UInput write and syn in a python shell works though. The program is executed as root. Raspberry Pi is running ArchLinuxARM and laptop is running Arch Linux.

**Comment by ssieb** [comment] 2015-09-05 02:35
It might be a timing issue.  There are a couple of things wrong with that code.  First, you don't need that inWaiting check because that is just going to put you in a tight cpu-burning loop.  Secondly, you should create the UInput device at the top like where you made the Serial device.  Otherwise, you are creating a new UInput device every time you want to make the mouse click.  I have no idea how well the X server will handle that but I really doubt it will have time to open the device before you send the click. Events don't queue up in an input device if there is no one listening.

**Comment by squgeim** [comment] 2015-09-05 03:25
Ok, I did not consider that.
However, it's still not working with the uinput device creation at the top.
Btw, I tried it with a new program with nothing but the uinput creation, btn left down, up, syn and close, and it doesn't work; thus proving that it is about the time, but how much time?
When running this bare program, it takes about 5 secs to exit. Is this the time required to create the device? I tried puting a sleep for 7secs after the device creation line, so the writing happens only after the device is created, still no success.
Is there some way of making sure the device is created before the program moves forward?

**Comment by gvalkov** [comment] 2015-09-06 12:28
Hello @squgeim,

Let's start by ensuring that the uinput module is loaded and the uinput device node exists:

```bash
$ modprobe uinput
$ stat /dev/uinput
```

If that works, it's time to test if we can set up the simplest uinput device:

```python
# uinput_test.py
from evdev import UInput, ecodes

ui = UInput()

for key in 'hello':
    ui.write(ecodes.EV_KEY, ecodes.ecodes['KEY_%s' % key.upper()], 1)
    ui.write(ecodes.EV_KEY, ecodes.ecodes['KEY_%s' % key.upper()], 0)

ui.syn()
input('Press enter to exit ... ')
ui.close()
```

When you run `python uinput_test.py`, you should see something along the lines of this on your console:

```
Press enter to exit ... hello
```

Before pressing enter, you may verify that the event device exists by running `evtest` (installable with `pacman -S evtest`). There should be a device named 'py-evdev-uinput`. You may also just compare the number of device in the `/dev/input/` directory before and after running the test script - if the code works, there should be one device more. Hit enter to exit the script and remove the dummy input device.

The input device creation should be instantaneous. Let me know if this simple test works so that we may decide how to proceed with the debugging. In the meantime, I'll try setting up arch on a RPy to test if I can reproduce your issue locally.

Thank you for reporting this. Having a working python-evdev on RPy-s is important to me. Also, thank you @ssieb for helping out with the troubleshooting.

**Comment by ssieb** [comment] 2015-09-07 05:30
Sorry for taking so long to get back to you.

After doing some testing, I'm surprised that it worked in any way you tried.  (Note that the following explanation is for a regular Linux system, I don't know if it works differently on a Pi.)  The problem is that the kernel examines the device when you create it to figure out what it is.  Since you have created a device with only buttons, it has no idea what it is.  Udev picks it up and passes to the X evdev driver, which just ignores it because it's unidentified.

The solution is to add relative or absolute motion events so that it looks like a mouse.  If you use absolute, you also get a joystick device.  I might have been wrong about the timing though.  On my laptop, I can run the script straight through including closing the device with no pauses and the click happens.

```python
u = UInput({e.EV_KEY : (e.BTN_LEFT, e.BTN_RIGHT), e.EV_REL:(e.REL_X,e.REL_Y)})
u = UInput({e.EV_KEY : (e.BTN_LEFT, e.BTN_RIGHT), e.EV_ABS:(e.ABS_X,e.ABS_Y)})
```

**Closed** 2018-08-27 18:11 UTC
